GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgdGl0bGUiLCJpZCI6IjYzMzllMTRhNTY1MWM3ZmMzODNjOTE2MCIsImlhdCI6MTY2NDc0MTAxMiwiZXhwIjoxNjY0NzQ0NjEyfQ.kO0vCLD3OI7Xf3nBJe8q2LlkmcpAXKDrTObEeFo2lSY

{
  "title": "test title",
  "author": "random author",
  "url": "http://blogtest.com/haha",
  "likes": 2
}
