GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "test title",
  "author": "random author",
  "url": "http://blogtest.com/haha",
  "likes": 2
}
