GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "test title",
  "name": "random author",
  "password": "randompassword"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "user2",
  "name": "user two",
  "password": "randompassword"
}
###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "xx",
  "name": "random author",
  "password": "randompassword"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "valid username",
  "name": "random author",
  "password": "xx"
}
